name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run tests
      run: |
        npm i
        npm run test

    - name: Nightly build
      run: |
        npm run release

    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist/

  docs:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate docs
        run: |
          npm i
          npm run docs

      - name: test
        run: ls

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          exclude_assets: node_modules
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
